name: lyrically
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  web: ^1.0.0
  url_launcher: ^6.3.0
  go_router: ^14.2.7

  yaml: ^3.1.2
  provider: ^6.1.2
  flutter_typeahead: ^5.2.0
  mesh_gradient: ^1.3.7
  glitters: ^0.4.0
  searchfield: ^1.0.9

  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoFlex
      fonts:
        - asset: fonts/RobotoFlex.ttf
    - family: Archivo
      fonts:
        - asset: fonts/Archivo.ttf